const sb=window.supabaseClient,$=s=>document.querySelector(s),app=$('#app'),status=$('#status');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function setStatus(t,ok=false){status.textContent=t;status.className=ok?'ok':'error'}
async function authView(){app.innerHTML='<section class="card auth-card"><h1>Welcome to MAX</h1><p class="muted">Connect, chat, call and use AI.</p><div class="tabs"><button id="loginTab">Sign in</button><button id="signupTab" class="secondary">Create account</button></div><form id="authForm"><div id="signupFields" hidden><label>Username</label><input id="username" minlength="3" maxlength="30"><label>Display name</label><input id="displayName" maxlength="80"></div><label>Email</label><input id="email" type="email" required><label>Password</label><input id="password" type="password" minlength="6" required><button id="submitAuth">Sign in</button></form><p id="formMessage" class="muted"></p></section>';let mode='login';$('#loginTab').onclick=()=>{mode='login';$('#signupFields').hidden=true;$('#submitAuth').textContent='Sign in'};$('#signupTab').onclick=()=>{mode='signup';$('#signupFields').hidden=false;$('#submitAuth').textContent='Create account'};$('#authForm').onsubmit=async e=>{e.preventDefault();try{if(mode==='login'){const r=await sb.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});if(r.error)throw r.error}else{const r=await sb.auth.signUp({email:$('#email').value.trim(),password:$('#password').value,options:{data:{display_name:$('#displayName').value.trim()}}});if(r.error)throw r.error;if(!r.data.session){$('#formMessage').textContent='Account created. Check your email, then sign in.';return}const p=await sb.from('profiles').upsert({id:r.data.user.id,username:$('#username').value.trim().toLowerCase(),display_name:$('#displayName').value.trim()});if(p.error)throw p.error}await render()}catch(e){$('#formMessage').textContent=e.message||'Authentication failed'}}}
async function profileView(user){const r=await sb.from('profiles').select('*').eq('id',user.id).single();if(r.error){setStatus(r.error.message);return}const p=r.data;app.innerHTML=`<section class="card"><div class="avatar">${esc((p.display_name||'M')[0]).toUpperCase()}</div><h1>${esc(p.display_name)}</h1><p class="muted">@${esc(p.username)}</p><form id="pf"><label>Display name</label><input id="pn" value="${esc(p.display_name)}" required><label>Username</label><input id="pu" value="${esc(p.username)}" required><label>Bio</label><textarea id="pb">${esc(p.bio||'')}</textarea><button>Save profile</button><button type="button" class="secondary" id="out">Sign out</button></form></section>`;$('#pf').onsubmit=async e=>{e.preventDefault();const r=await sb.from('profiles').update({display_name:$('#pn').value.trim(),username:$('#pu').value.trim().toLowerCase(),bio:$('#pb').value.trim()}).eq('id',user.id);if(r.error)setStatus(r.error.message);else{setStatus('Profile saved.',true);profileView(user)}};$('#out').onclick=async()=>{await sb.auth.signOut();render()}}
async function feedView(user){app.innerHTML='<section class="grid"><aside class="card profile-card"><h2>MAX</h2><nav><button id="feedBtn">🏠 Feed</button><button id="profileBtn">👤 Profile</button><button id="notifyBtn">🔔 Notifications</button><button id="logoutBtn">🚪 Sign out</button></nav></aside><section><div class="card"><h2>Create a post</h2><form id="postForm"><textarea id="postText" maxlength="5000" placeholder="What’s on your mind?" required></textarea><button>Post</button></form></div><div id="feed" class="card" style="margin-top:20px"><p class="muted">Loading posts…</p></div></section></section>';
$('#profileBtn').onclick=()=>profileView(user);$('#feedBtn').onclick=()=>feedView(user);$('#logoutBtn').onclick=async()=>{await sb.auth.signOut();render()};$('#notifyBtn').onclick=()=>notificationsView(user);$('#postForm').onsubmit=async e=>{e.preventDefault();const text=$('#postText').value.trim();if(!text)return;const r=await sb.from('posts').insert({author_id:user.id,content:text});if(r.error)setStatus(r.error.message);else{$('#postText').value='';loadFeed(user)}};loadFeed(user);sb.channel('feed-live').on('postgres_changes',{event:'*',schema:'public',table:'posts'},()=>loadFeed(user)).subscribe()}
async function loadFeed(user){const r=await sb.from('posts').select('id,author_id,content,created_at,profiles(display_name,username)').order('created_at',{ascending:false}).limit(50);if(r.error){$('#feed').innerHTML='<p>'+esc(r.error.message)+'</p>';return}if(!r.data.length){$('#feed').innerHTML='<p class="muted">No posts yet. Be the first to post.</p>';return}$('#feed').innerHTML=r.data.map(p=>`<article class="post"><strong>${esc(p.profiles?.display_name||'User')}</strong> <small>@${esc(p.profiles?.username||'user')}</small><small> · ${new Date(p.created_at).toLocaleString()}</small><p>${esc(p.content)}</p><div><button data-like="${p.id}">❤️ Like</button><button data-comment="${p.id}">💬 Comment</button></div><div id="comments-${p.id}"></div></article>`).join('');for(const p of r.data){loadLikes(p.id);loadComments(p.id,user)}document.querySelectorAll('[data-like]').forEach(b=>b.onclick=()=>toggleLike(b.dataset.like,user));document.querySelectorAll('[data-comment]').forEach(b=>b.onclick=()=>commentBox(b.dataset.comment,user))}
async function loadLikes(id){const r=await sb.from('post_likes').select('user_id',{count:'exact',head:true}).eq('post_id',id);const b=document.querySelector(`[data-like="${id}"]`);if(b)b.textContent=`❤️ Like (${r.count||0})`}
async function toggleLike(id,user){const x=await sb.from('post_likes').select('post_id').eq('post_id',id).eq('user_id',user.id).maybeSingle();if(x.data)await sb.from('post_likes').delete().eq('post_id',id).eq('user_id',user.id);else await sb.from('post_likes').insert({post_id:id,user_id:user.id});loadLikes(id)}
async function loadComments(id,user){const r=await sb.from('post_comments').select('id,content,created_at,profiles(display_name)').eq('post_id',id).order('created_at').limit(20);const el=$(`#comments-${id}`);if(el)el.innerHTML=(r.data||[]).map(c=>`<p class="comment"><strong>${esc(c.profiles?.display_name||'User')}</strong>: ${esc(c.content)}</p>`).join('')}
async function commentBox(id,user){const text=prompt('Write a comment');if(!text?.trim())return;const r=await sb.from('post_comments').insert({post_id:id,author_id:user.id,content:text.trim()});if(r.error)setStatus(r.error.message);else loadComments(id,user)}
async function notificationsView(user){const r=await sb.from('notifications').select('*').eq('user_id',user.id).order('created_at',{ascending:false}).limit(50);app.innerHTML='<section class="card"><button id="back">← Back</button><h1>Notifications</h1>'+((r.data||[]).length?(r.data||[]).map(n=>`<div class="notification"><strong>${esc(n.title)}</strong><p>${esc(n.body||'')}</p><small>${new Date(n.created_at).toLocaleString()}</small></div>`).join(''):'<p class="muted">No notifications yet.</p>')+'</section>';$('#back').onclick=()=>feedView(user)}
async function render(){const r=await sb.auth.getUser();if(!r.data.user){$('#topActions').innerHTML='';authView();return}const u=r.data.user;$('#topActions').innerHTML='<span class="muted">Online</span>';feedView(u)}
sb.auth.onAuthStateChange(()=>render());render();