(()=>{
'use strict';
const sb=window.supabaseClient;
let recorder=null,chunks=[],startedAt=0,timer=null,button=null,currentConversation=null;
const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const flash=t=>{const s=$('#status');if(!s)return;s.textContent=t;s.className='error';clearTimeout(flash.t);flash.t=setTimeout(()=>{s.textContent='';s.className=''},3500)};
function preferredMime(){const types=['audio/webm;codecs=opus','audio/webm','audio/ogg;codecs=opus','audio/mp4'];return types.find(t=>MediaRecorder.isTypeSupported?.(t))||''}
function stopTimer(){if(timer){clearInterval(timer);timer=null}}
function setRecording(on){if(!button)return;button.classList.toggle('recording',on);button.setAttribute('aria-label',on?'Stop recording':'Record voice note');button.title=on?'Stop recording':'Record voice note';button.innerHTML=on?'<span class="audio-note-stop">■</span><small>Stop</small>':'<span>🎙</span>'}
function ensureButton(){const form=$('#chatCompose');if(!form||button?.isConnected)return;if(form.dataset.audioNoteWired==='1')return;form.dataset.audioNoteWired='1';button=document.createElement('button');button.type='button';button.id='audioNoteButton';button.className='audio-note-btn';button.setAttribute('aria-label','Record voice note');button.title='Record voice note';button.innerHTML='<span>🎙</span>';const submit=form.querySelector('button[type="submit"]');form.insertBefore(button,submit||null);button.onclick=toggleRecording}
async function toggleRecording(){if(recorder?.state==='recording'){recorder.stop();return}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){flash('Voice notes are not supported by this browser.');return}if(!window.activeConversationId){flash('Open a conversation first.');return}currentConversation=window.activeConversationId;try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const mime=preferredMime();recorder=mime?new MediaRecorder(stream,{mimeType:mime}):new MediaRecorder(stream);chunks=[];startedAt=Date.now();setRecording(true);button.querySelector('small')?.remove();const label=document.createElement('small');label.className='audio-note-timer';label.textContent='0:00';button.appendChild(label);timer=setInterval(()=>{const sec=Math.floor((Date.now()-startedAt)/1000);label.textContent=`${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`},250);recorder.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data)};recorder.onstop=async()=>{stopTimer();setRecording(false);stream.getTracks().forEach(t=>t.stop());const blob=new Blob(chunks,{type:recorder.mimeType||mime||'audio/webm'});recorder=null;chunks=[];if(!blob.size||!currentConversation)return;await uploadAudio(blob,currentConversation)};recorder.start(250)}catch(e){stopTimer();setRecording(false);recorder=null;flash(e?.message||'Microphone access was denied.')}}
async function uploadAudio(blob,conversationId){try{if(blob.size>10*1024*1024)throw new Error('Voice note must be 10 MB or smaller.');const ext=blob.type.includes('ogg')?'ogg':blob.type.includes('mp4')?'m4a':'webm';const path=`${window.__MAX_USER?.id||'unknown'}/messages/${crypto.randomUUID()}.${ext}`;const up=await sb.storage.from('post-media').upload(path,blob,{contentType:blob.type||'audio/webm',upsert:false});if(up.error)throw up.error;const url=sb.storage.from('post-media').getPublicUrl(path).data.publicUrl;const me=window.__MAX_USER|| (await sb.auth.getUser()).data.user;if(!me)throw new Error('Session expired.');const r=await sb.from('messages').insert({conversation_id:conversationId,sender_id:me.id,type:'audio',content:null,attachment_url:url});if(r.error)throw r.error}catch(e){flash(e?.message||'Could not send voice note')}}
async function enhanceAudioMessages(){const id=window.activeConversationId;if(!id)return;const me=window.__MAX_USER;if(!me)return;const r=await sb.from('messages').select('id,type,attachment_url,created_at').eq('conversation_id',id).eq('type','audio').order('created_at',{ascending:true}).limit(300);if(r.error)return;const bubbles=$$('#chatMessages .bubble');if(!bubbles.length)return;const rows=r.data||[];for(const row of rows){const existing=document.querySelector(`[data-audio-id="${row.id}"]`);if(existing)continue;const bubble=bubbles.find(b=>b.textContent.includes(new Date(row.created_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})));if(!bubble)continue;const audio=document.createElement('div');audio.className='audio-note-player';audio.dataset.audioId=row.id;audio.innerHTML=`<button type="button" class="audio-note-play">▶</button><audio preload="metadata" src="${row.attachment_url}"></audio><span class="audio-note-label">Voice note</span>`;const player=$('.audio-note-play',audio),media=$('audio',audio);player.onclick=()=>{if(media.paused){$$('audio',document).forEach(a=>{if(a!==media)a.pause()});media.play().then(()=>player.textContent='❚❚').catch(()=>{});media.onended=()=>player.textContent='▶'}else{media.pause();player.textContent='▶'}};bubble.prepend(audio)}}
function observe(){const root=$('#app')||document.body;const mo=new MutationObserver(()=>{ensureButton();if(window.activeConversationId!==currentConversation){currentConversation=window.activeConversationId;setTimeout(enhanceAudioMessages,100)}else setTimeout(enhanceAudioMessages,40)});mo.observe(root,{childList:true,subtree:true});setTimeout(ensureButton,300)}
window.addEventListener('beforeunload',()=>{stopTimer();if(recorder?.state==='recording')recorder.stop()});observe();
})();
