(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s);
function flash(t){const s=$('#status');if(!s)return;s.textContent=t;s.className='error';clearTimeout(flash.t);flash.t=setTimeout(()=>{s.textContent='';s.className=''},3200)}
let draftTimer=null;
function key(){return `max:create-draft:${window.__MAX_USER?.id||'guest'}`}
function getDraft(){try{return JSON.parse(localStorage.getItem(key())||'null')}catch{return null}}
function saveDraft(){const panel=$('#creatorPanel');if(!panel||panel.hidden)return;const type=panel.dataset.createType||'';const text=$('#textBody')?.value||$('#mediaCaption')?.value||'';const style=$('#textCanvas')?.className.match(/style-([a-z0-9_-]+)/)?.[1]||'midnight';localStorage.setItem(key(),JSON.stringify({type,text,style,savedAt:Date.now()}));const badge=$('#draftBadge');if(badge)badge.textContent='Draft saved'}
function restoreDraft(){const d=getDraft();if(!d)return;const oldType=d.type;const oldText=d.text||'';if(oldType==='text'&&$('#textBody')){$('#textBody').value=oldText;$('#textCanvas').className=`text-canvas style-${d.style||'midnight'}`}
else if($('#mediaCaption'))$('#mediaCaption').value=oldText;const badge=$('#draftBadge');if(badge)badge.textContent='Draft restored'}
function clearDraft(){localStorage.removeItem(key());$('#draftBadge')&&( $('#draftBadge').textContent='Draft cleared')}
function addDraftBar(type){const panel=$('#creatorPanel');if(!panel)return;panel.dataset.createType=type;const head=$('.creator-head',panel);if(head&&!$('.create-draftbar',panel))head.insertAdjacentHTML('beforeend',`<div class="create-draftbar"><span id="draftBadge">Draft ready</span><button type="button" id="clearDraftBtn">Discard draft</button></div>`);$('#clearDraftBtn')?.addEventListener('click',()=>{if(confirm('Discard this draft?')){clearDraft();const text=$('#textBody')||$('#mediaCaption');if(text)text.value=''}} ,{once:true});restoreDraft();panel.addEventListener('input',()=>{clearTimeout(draftTimer);draftTimer=setTimeout(saveDraft,350)},{once:false});panel.addEventListener('change',()=>{clearTimeout(draftTimer);draftTimer=setTimeout(saveDraft,350)},{once:false})}
function addMediaTools(){const panel=$('#creatorPanel'),input=$('#mediaInput'),preview=$('#previewBox');if(!panel||!input||!preview||$('.media-studio-tools',panel))return;const tools=document.createElement('div');tools.className='media-studio-tools';tools.innerHTML=`<div class="studio-meta"><span id="mediaMeta">Choose a file to begin</span><div><button type="button" id="replaceMedia" class="studio-btn">Replace</button><button type="button" id="removeMedia" class="studio-btn subtle">Remove</button></div></div><div class="studio-tip">Tip: use a vertical video for the best MAX feed experience.</div>`;preview.after(tools);$('#replaceMedia').onclick=()=>input.click();$('#removeMedia').onclick=()=>{input.value='';preview.innerHTML='';$('#mediaMeta').textContent='Choose a file to begin'};input.addEventListener('change',()=>{const f=input.files?.[0];if(f)$('#mediaMeta').textContent=`${f.name} • ${Math.max(1,Math.round(f.size/1024/1024*10)/10)} MB`});}
function addPreviewAction(){const panel=$('#creatorPanel');if(!panel||$('.review-row',panel))return;const publish=$('#publishMedia')||$('#publishText');if(!publish)return;const row=document.createElement('div');row.className='review-row';row.innerHTML='<button type="button" class="secondary" id="previewCreate">Preview</button><span>Review your post before publishing.</span>';publish.before(row);$('#previewCreate').onclick=()=>openPreview()}
function openPreview(){const panel=$('#creatorPanel');if(!panel)return;const media=$('#previewBox img, #previewBox video');const text=$('#textBody')?.value||'';const caption=$('#mediaCaption')?.value||'';const canvas=$('#textCanvas');const style=canvas?.className.match(/style-([a-z0-9_-]+)/)?.[1]||'midnight';document.body.insertAdjacentHTML('beforeend',`<div class="create-preview-modal" id="createPreviewModal"><section class="create-preview-card"><header><div><span>PREVIEW</span><h2>Before you publish</h2></div><button id="closeCreatePreview" class="preview-close">×</button></header><div class="preview-post">${canvas?`<div class="preview-text style-${style}">${escText(text)}</div>`:(media?media.cloneNode(true).outerHTML:'<div class="preview-empty">No media selected.</div>')} ${caption?`<p>${escText(caption)}</p>`:''}</div><footer><button class="secondary" id="backCreatePreview">Keep editing</button><button class="primary" id="publishFromPreview">Publish</button></footer></section></div>`);const close=()=>$('#createPreviewModal')?.remove();$('#closeCreatePreview').onclick=close;$('#backCreatePreview').onclick=close;$('#publishFromPreview').onclick=()=>{close();($(`${panel.id?`#${panel.id}`:''}`)||panel);const b=$('#publishMedia')||$('#publishText');b?.click()}}
function escText(v){return String(v||'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
function enhance(){const panel=$('#creatorPanel');if(!panel||panel.hidden||panel.dataset.enhanced==='1')return;panel.dataset.enhanced='1';const type=panel.dataset.createType||($('.creator-head .kicker',panel)?.textContent||'').toLowerCase();addDraftBar(type);if($('#mediaInput'))addMediaTools();addPreviewAction()}
const mo=new MutationObserver(()=>setTimeout(enhance,50));mo.observe(document.getElementById('app')||document.body,{childList:true,subtree:true});setTimeout(enhance,500);
})();
