(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s);
function key(){return `max:create-draft:${window.__MAX_USER?.id||'guest'}`}
function getDraft(){try{return JSON.parse(localStorage.getItem(key())||'null')}catch{return null}}
function saveDraft(panel){if(!panel||panel.hidden)return;const type=panel.dataset.createType||'';const text=$('#textBody',panel)?.value||$('#mediaCaption',panel)?.value||'';const style=$('#textCanvas',panel)?.className.match(/style-([a-z0-9_-]+)/)?.[1]||'midnight';localStorage.setItem(key(),JSON.stringify({type,text,style,savedAt:Date.now()}));$('#draftBadge',panel)?.replaceChildren(document.createTextNode('Draft saved'))}
function restoreDraft(panel){const d=getDraft();if(!d)return;const text=$('#textBody',panel)||$('#mediaCaption',panel);if(text)text.value=d.text||'';if(d.type==='text'&&$('#textCanvas',panel))$('#textCanvas',panel).className=`text-canvas style-${d.style||'midnight'}`;$('#draftBadge',panel)?.replaceChildren(document.createTextNode('Draft restored'))}
function clearDraft(panel){localStorage.removeItem(key());const text=$('#textBody',panel)||$('#mediaCaption',panel);if(text){text.value='';text.dispatchEvent(new Event('input',{bubbles:true}))}$('#draftBadge',panel)?.replaceChildren(document.createTextNode('Draft cleared'))}
function addDraftBar(panel,type){panel.dataset.createType=type;const head=$('.creator-head',panel);if(head&&!$('.create-draftbar',panel)){head.insertAdjacentHTML('beforeend',`<div class="create-draftbar"><span id="draftBadge">Draft ready</span><button type="button" id="clearDraftBtn">Discard draft</button></div>`)}const btn=$('#clearDraftBtn',panel);if(btn&&!btn.dataset.wired){btn.dataset.wired='1';btn.addEventListener('click',()=>{const bar=btn.closest('.create-draftbar');if(bar?.querySelector('.discard-confirm'))return;const confirm=document.createElement('div');confirm.className='discard-confirm';confirm.innerHTML='<span>Discard this draft?</span><button type="button" data-discard="yes">Discard</button><button type="button" data-discard="no">Keep</button>';bar.appendChild(confirm);confirm.querySelector('[data-discard="yes"]').onclick=()=>{clearDraft(panel);confirm.remove()};confirm.querySelector('[data-discard="no"]').onclick=()=>confirm.remove()})}restoreDraft(panel);if(!panel.dataset.draftWired){panel.dataset.draftWired='1';panel.addEventListener('input',()=>{clearTimeout(panel._draftTimer);panel._draftTimer=setTimeout(()=>saveDraft(panel),350)});panel.addEventListener('change',()=>{clearTimeout(panel._draftTimer);panel._draftTimer=setTimeout(()=>saveDraft(panel),350)})}}
function addMediaTools(panel){const input=$('#mediaInput',panel),preview=$('#previewBox',panel);if(!input||!preview||$('.media-studio-tools',panel))return;const tools=document.createElement('div');tools.className='media-studio-tools';tools.innerHTML='<div class="studio-meta"><span id="mediaMeta">Choose a file to begin</span><div><button type="button" id="replaceMedia" class="studio-btn">Replace</button><button type="button" id="removeMedia" class="studio-btn subtle">Remove</button></div></div><div class="studio-tip">Vertical video works best in the MAX feed.</div>';preview.after(tools);$('#replaceMedia',tools).onclick=()=>input.click();$('#removeMedia',tools).onclick=()=>{input.value='';preview.innerHTML='';$('#mediaMeta',tools).textContent='Choose a file to begin'};if(!input.dataset.metaWired){input.dataset.metaWired='1';input.addEventListener('change',()=>{const f=input.files?.[0];if(f)$('#mediaMeta',tools).textContent=`${f.name} • ${Math.max(1,Math.round(f.size/1024/1024*10)/10)} MB`})}}
function addPreviewAction(panel){if($('.review-row',panel))return;const publish=$('#publishMedia',panel)||$('#publishText',panel);if(!publish)return;const row=document.createElement('div');row.className='review-row';row.innerHTML='<button type="button" class="secondary" id="previewCreate">Preview</button><span>Review your post before publishing.</span>';publish.before(row);$('#previewCreate',row).onclick=()=>openPreview(panel)}
function escText(v){return String(v||'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
function openPreview(panel){const media=$('#previewBox img, #previewBox video',panel);const text=$('#textBody',panel)?.value||'';const caption=$('#mediaCaption',panel)?.value||'';const canvas=$('#textCanvas',panel);const style=canvas?.className.match(/style-([a-z0-9_-]+)/)?.[1]||'midnight';document.body.insertAdjacentHTML('beforeend',`<div class="create-preview-modal" id="createPreviewModal"><section class="create-preview-card"><header><div><span>PREVIEW</span><h2>Before you publish</h2></div><button type="button" id="closeCreatePreview" class="preview-close">×</button></header><div class="preview-post">${canvas?`<div class="preview-text style-${style}">${escText(text)}</div>`:(media?media.cloneNode(true).outerHTML:'<div class="preview-empty">No media selected.</div>')}${caption?`<p>${escText(caption)}</p>`:''}</div><footer><button type="button" class="secondary" id="backCreatePreview">Keep editing</button><button type="button" class="primary" id="publishFromPreview">Publish</button></footer></section></div>`);const close=()=>$('#createPreviewModal')?.remove();$('#closeCreatePreview').onclick=close;$('#backCreatePreview').onclick=close;$('#publishFromPreview').onclick=()=>{close();($('#publishMedia',panel)||$('#publishText',panel))?.click()}}
function removeCameraCard(){document.querySelectorAll('.create-card.camera,[data-create-type="camera"],.create-option.camera').forEach(el=>el.remove())}
function enhance(){removeCameraCard();const panel=$('#creatorPanel');if(!panel||panel.hidden)return;const type=panel.dataset.createType||($('.creator-head .kicker',panel)?.textContent||'').toLowerCase();addDraftBar(panel,type);if($('#mediaInput',panel))addMediaTools(panel);addPreviewAction(panel)}
const mo=new MutationObserver(()=>setTimeout(enhance,30));mo.observe(document.getElementById('app')||document.body,{childList:true,subtree:true});setTimeout(enhance,250);
})();
