(()=>{
'use strict';
const sb=window.supabaseClient;
let me=null,signalChannel=null,sessionId=null,pc=null,localStream=null,remoteStream=null,selectedPeer=null,currentKind=null,makingCall=false,creatingOffer=false;
const $=(s,r=document)=>r.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
async function user(){if(me)return me;const r=await sb.auth.getUser();if(r.error||!r.data.user)return null;me=r.data.user;return me}
async function findConversation(other){const u=await user();if(!u)return null;const a=await sb.from('conversation_members').select('conversation_id').eq('user_id',u.id);if(a.error)throw a.error;const ids=(a.data||[]).map(x=>x.conversation_id);if(!ids.length)return null;const b=await sb.from('conversation_members').select('conversation_id').eq('user_id',other).in('conversation_id',ids);if(b.error)throw b.error;return b.data?.[0]?.conversation_id||null}
function stopSignaling(){if(signalChannel){sb.removeChannel(signalChannel);signalChannel=null}}
function cleanup(){stopSignaling();if(pc){pc.onicecandidate=null;pc.ontrack=null;pc.onconnectionstatechange=null;pc.close();pc=null}if(localStream){localStream.getTracks().forEach(t=>t.stop());localStream=null}remoteStream=null;sessionId=null;selectedPeer=null;currentKind=null;makingCall=false;creatingOffer=false;$('#maxCallOverlay')?.remove();$('#maxIncomingCall')?.remove()}
function renderCall(name,kind,status){$('#maxCallOverlay')?.remove();const letter=(name||'M').trim().charAt(0).toUpperCase()||'M';document.body.insertAdjacentHTML('beforeend',`<section id="maxCallOverlay" class="max-call-overlay"><header class="max-call-top"><span class="avatar">${esc(letter)}</span><div><div class="max-call-title">${esc(name||'MAX contact')}</div><div class="max-call-status" id="maxCallStatus">${esc(status||'Connecting…')}</div></div></header><div class="max-call-video-stage"><div class="max-call-avatar" id="maxCallAvatar">${esc(letter)}</div><video id="maxCallRemote" class="max-call-remote" autoplay playsinline></video><video id="maxCallLocal" class="max-call-local" autoplay muted playsinline></video></div><div class="max-call-controls"><button type="button" class="max-call-control" id="maxMute">🎙</button>${kind==='video'?'<button type="button" class="max-call-control" id="maxCamera">▣</button>':''}<button type="button" class="max-call-control end" id="maxEnd">✕</button></div></section>`);$('#maxEnd').onclick=()=>endCall('ended');$('#maxMute').onclick=()=>{const t=localStream?.getAudioTracks?.()[0];if(t){t.enabled=!t.enabled;$('#maxMute').classList.toggle('active',!t.enabled)}};$('#maxCamera')?.addEventListener('click',()=>{const t=localStream?.getVideoTracks?.()[0];if(t){t.enabled=!t.enabled;$('#maxCamera').classList.toggle('active',!t.enabled)}})}
function incoming(call,name,kind){$('#maxIncomingCall')?.remove();document.body.insertAdjacentHTML('beforeend',`<section id="maxIncomingCall" class="max-call-incoming"><h3>${esc(name||'MAX user')}</h3><p>Incoming ${kind==='video'?'video':'voice'} call</p><div class="max-call-incoming-actions"><button class="max-call-decline" id="maxDecline">Decline</button><button class="max-call-accept" id="maxAccept">Accept</button></div></section>`);$('#maxDecline').onclick=()=>respondIncoming(call,false);$('#maxAccept').onclick=()=>respondIncoming(call,true)}
async function addSignal(kind,payload){if(!sessionId||!me)return;const r=await sb.from('call_signals').insert({call_id:sessionId,sender_id:me.id,kind,payload});if(r.error)throw r.error}
async function handleSignal(s){if(!pc||s.sender_id===me.id)return;try{if(s.kind==='offer'){if(pc.currentRemoteDescription)return;await pc.setRemoteDescription(s.payload);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);await addSignal('answer',pc.localDescription)}else if(s.kind==='answer'){await pc.setRemoteDescription(s.payload)}else if(s.kind==='ice'&&s.payload){await pc.addIceCandidate(s.payload)}else if(s.kind==='hangup'){cleanup()}}catch(e){console.warn('MAX call signal:',e)}}
async function watchSignals(){stopSignaling();signalChannel=sb.channel(`max-call-signals-${sessionId}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'call_signals',filter:`call_id=eq.${sessionId}`},payload=>handleSignal(payload.new)).subscribe();const r=await sb.from('call_signals').select('sender_id,kind,payload,created_at').eq('call_id',sessionId).order('created_at',{ascending:true});if(!r.error)for(const s of r.data||[])await handleSignal(s)}
async function buildPeer(other,kind,name){pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});remoteStream=new MediaStream();renderCall(name,kind,'Connecting…');$('#maxCallRemote').srcObject=remoteStream;pc.ontrack=e=>e.streams?.[0]?.getTracks().forEach(t=>remoteStream.addTrack(t));pc.onicecandidate=e=>{if(e.candidate)addSignal('ice',e.candidate).catch(()=>{})};pc.onconnectionstatechange=()=>{const s=pc.connectionState;if(s==='connected')$('#maxCallStatus').textContent='Connected';if(s==='failed')endCall('failed')};localStream=await navigator.mediaDevices.getUserMedia({audio:true,video:kind==='video'});$('#maxCallLocal').srcObject=localStream;localStream.getTracks().forEach(t=>pc.addTrack(t,localStream));await watchSignals()}
async function startCall(otherId,name,kind){const u=await user();if(!u||makingCall)return;makingCall=true;try{const conversationId=await findConversation(otherId);if(!conversationId)throw new Error('Open the conversation before calling.');selectedPeer={id:otherId,name};currentKind=kind;const r=await sb.from('call_sessions').insert({conversation_id:conversationId,caller_id:u.id,callee_id:otherId,kind,status:'ringing'}).select('id').single();if(r.error)throw r.error;sessionId=r.data.id;await buildPeer(otherId,kind,name);creatingOffer=true;const offer=await pc.createOffer();await pc.setLocalDescription(offer);await addSignal('offer',pc.localDescription);creatingOffer=false;$('#maxCallStatus').textContent='Ringing…'}catch(e){cleanup();alert(e.message||'Could not start call')}finally{makingCall=false;creatingOffer=false}}
async function respondIncoming(call,accept){$('#maxIncomingCall')?.remove();const u=await user();if(!u)return;sessionId=call.id;selectedPeer={id:call.caller_id,name:call.caller_name};currentKind=call.kind;if(!accept){await sb.from('call_sessions').update({status:'declined',ended_at:new Date().toISOString()}).eq('id',call.id);await addSignal('hangup',{}).catch(()=>{});cleanup();return}await sb.from('call_sessions').update({status:'accepted',answered_at:new Date().toISOString()}).eq('id',call.id);await buildPeer(call.caller_id,call.kind,call.caller_name);const offer=(await sb.from('call_signals').select('sender_id,payload').eq('call_id',call.id).eq('kind','offer').order('created_at',{ascending:false}).limit(1)).data?.[0];if(offer)await handleSignal({sender_id:offer.sender_id,kind:'offer',payload:offer.payload})}
async function endCall(status){if(sessionId){await sb.from('call_sessions').update({status,ended_at:new Date().toISOString()}).eq('id',sessionId);if(me)await addSignal('hangup',{}).catch(()=>{})}cleanup()}
function installButtons(){const head=$('.conversation-head');if(!head||head.dataset.maxCalls==='1')return;head.dataset.maxCalls='1';const wrap=document.createElement('div');wrap.className='max-call-actions';wrap.innerHTML='<button type="button" class="max-call-btn" id="maxVoiceCall" aria-label="Voice call">☎</button><button type="button" class="max-call-btn" id="maxVideoCall" aria-label="Video call">▣</button>';head.appendChild(wrap);$('#maxVoiceCall').onclick=()=>{const id=window.__MAX_CHAT_OTHER_USER_ID;if(id)startCall(id,$('#chatName').textContent,'voice')};$('#maxVideoCall').onclick=()=>{const id=window.__MAX_CHAT_OTHER_USER_ID;if(id)startCall(id,$('#chatName').textContent,'video')}}
function watchConversation(){document.addEventListener('click',e=>{const p=e.target.closest?.('[data-person]');if(p){window.__MAX_CHAT_OTHER_USER_ID=p.dataset.person;setTimeout(installButtons,150)}if(e.target.closest?.('#backPeople')){delete window.__MAX_CHAT_OTHER_USER_ID;cleanup()}})}
async function watchIncoming(){const u=await user();if(!u)return;const ch=sb.channel(`max-call-invite-${u.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'call_sessions',filter:`callee_id=eq.${u.id}`},async p=>{const c=p.new;if(c.status!=='ringing')return;const prof=await sb.from('profiles').select('display_name,username').eq('id',c.caller_id).maybeSingle();const name=prof.data?.display_name||prof.data?.username||'MAX user';incoming({...c,caller_name:name})}).subscribe();window.__MAX_CALL_INVITE_CHANNEL=ch}
window.MAXStartCall=startCall;window.MAXEndCall=endCall;window.addEventListener('beforeunload',cleanup);(async()=>{await user();watchConversation();await watchIncoming()})();
})();