(()=>{
'use strict';
const sb=window.supabaseClient;
let me=null,signalChannel=null,sessionId=null,pc=null,localStream=null,remoteStream=null,selectedPeer=null,currentKind=null,makingCall=false;
const $=(s,r=document)=>r.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
async function user(){if(me)return me;const r=await sb.auth.getUser();if(r.error||!r.data.user)return null;me=r.data.user;return me}
function stopSignaling(){if(signalChannel){sb.removeChannel(signalChannel);signalChannel=null}}
function cleanup(){stopSignaling();if(pc){pc.onicecandidate=null;pc.ontrack=null;pc.onconnectionstatechange=null;pc.close();pc=null}if(localStream){localStream.getTracks().forEach(t=>t.stop());localStream=null}remoteStream=null;sessionId=null;selectedPeer=null;currentKind=null;makingCall=false;$('#maxCallOverlay')?.remove();$('#maxIncomingCall')?.remove()}
function renderCall(name,kind,status){$('#maxCallOverlay')?.remove();const letter=(name||'M').trim().charAt(0).toUpperCase()||'M';document.body.insertAdjacentHTML('beforeend',`<section id="maxCallOverlay" class="max-call-overlay" role="dialog" aria-modal="true"><header class="max-call-top"><button type="button" class="max-call-close" id="maxCallMin" aria-label="Minimize call">⌄</button><span class="avatar">${esc(letter)}</span><div class="max-call-identity"><div class="max-call-title">${esc(name||'MAX contact')}</div><div class="max-call-status" id="maxCallStatus">${esc(status||'Connecting…')}</div></div></header><div class="max-call-video-stage"><div class="max-call-bg"></div><div class="max-call-avatar" id="maxCallAvatar">${esc(letter)}</div><video id="maxCallRemote" class="max-call-remote" autoplay playsinline></video><video id="maxCallLocal" class="max-call-local" autoplay muted playsinline></video><div class="max-call-live-pill" id="maxCallLive">${kind==='video'?'VIDEO':'VOICE'}</div></div><div class="max-call-controls"><button type="button" class="max-call-control" id="maxMute"><span>🎙</span><small>Mute</small></button>${kind==='video'?'<button type="button" class="max-call-control" id="maxCamera"><span>◉</span><small>Camera</small></button>':''}<button type="button" class="max-call-control end" id="maxEnd"><span>✕</span><small>End</small></button></div></section>`);$('#maxCallMin').onclick=()=>{$('#maxCallOverlay')?.classList.toggle('minimized')};$('#maxEnd').onclick=()=>endCall('ended');$('#maxMute').onclick=()=>{const t=localStream?.getAudioTracks?.()[0];if(t){t.enabled=!t.enabled;$('#maxMute').classList.toggle('active',!t.enabled)}};$('#maxCamera')?.addEventListener('click',()=>{const t=localStream?.getVideoTracks?.()[0];if(t){t.enabled=!t.enabled;$('#maxCamera').classList.toggle('active',!t.enabled)}})}
function incoming(call){$('#maxIncomingCall')?.remove();document.body.insertAdjacentHTML('beforeend',`<section id="maxIncomingCall" class="max-call-incoming" role="dialog" aria-modal="true"><div class="incoming-pulse"><span class="avatar">${esc((call.caller_name||'M').trim().charAt(0).toUpperCase())}</span></div><div class="incoming-copy"><strong>${esc(call.caller_name||'MAX user')}</strong><span>Incoming ${call.kind==='video'?'video':'voice'} call</span></div><div class="max-call-incoming-actions"><button class="max-call-decline" id="maxDecline">Decline</button><button class="max-call-accept" id="maxAccept">Accept</button></div></section>`);$('#maxDecline').onclick=()=>respondIncoming(call,false);$('#maxAccept').onclick=()=>respondIncoming(call,true)}
async function addSignal(kind,payload){if(!sessionId||!me)return;const r=await sb.from('call_signals').insert({call_id:sessionId,sender_id:me.id,kind,payload});if(r.error)throw r.error}
async function handleSignal(s){if(!pc||s.sender_id===me.id)return;try{if(s.kind==='offer'){if(pc.currentRemoteDescription)return;await pc.setRemoteDescription(s.payload);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);await addSignal('answer',pc.localDescription)}else if(s.kind==='answer'){await pc.setRemoteDescription(s.payload)}else if(s.kind==='ice'&&s.payload){await pc.addIceCandidate(s.payload)}else if(s.kind==='hangup'){cleanup()}}catch(e){console.warn('MAX call signal:',e)}}
async function watchSignals(){stopSignaling();signalChannel=sb.channel(`max-call-signals-${sessionId}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'call_signals',filter:`call_id=eq.${sessionId}`},payload=>handleSignal(payload.new)).subscribe();const r=await sb.from('call_signals').select('sender_id,kind,payload,created_at').eq('call_id',sessionId).order('created_at',{ascending:true});if(!r.error)for(const s of r.data||[])await handleSignal(s)}
async function buildPeer(other,kind,name,status){pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});remoteStream=new MediaStream();pc.ontrack=e=>e.streams?.[0]?.getTracks().forEach(t=>remoteStream.addTrack(t));pc.onicecandidate=e=>{if(e.candidate)addSignal('ice',e.candidate).catch(()=>{})};pc.onconnectionstatechange=()=>{const s=pc.connectionState;if(s==='connected'&&$('#maxCallStatus'))$('#maxCallStatus').textContent='Connected';if(s==='failed')endCall('failed')};localStream=await navigator.mediaDevices.getUserMedia({audio:true,video:kind==='video'});renderCall(name,kind,status||'Connecting…');const remote=$('#maxCallRemote');if(remote)remote.srcObject=remoteStream;const local=$('#maxCallLocal');if(local)local.srcObject=localStream;localStream.getTracks().forEach(t=>pc.addTrack(t,localStream));await watchSignals()}
async function findActivePeer(){const u=await user();const conversationId=window.activeConversationId;console.log('[CALL DEBUG] activeConversationId:',conversationId);if(!u||!conversationId)return null;const r=await sb.from('conversation_members').select('user_id').eq('conversation_id',conversationId).neq('user_id',u.id).limit(1).maybeSingle();if(r.error)throw r.error;return r.data?.user_id||null}
async function startCall(otherId,name,kind){const u=await user();if(!u||makingCall)return;makingCall=true;const conversationId=window.activeConversationId;console.log('[CALL DEBUG] activeConversationId:',conversationId);console.log('[CALL DEBUG] current conversation:',conversationId);try{if(!conversationId)throw new Error('No active conversation. Open a chat before calling.');if(!otherId)throw new Error('No call recipient found.');selectedPeer={id:otherId,name};currentKind=kind;const r=await sb.from('call_sessions').insert({conversation_id:conversationId,caller_id:u.id,callee_id:otherId,kind,status:'ringing'}).select('id').single();if(r.error)throw r.error;sessionId=r.data.id;await buildPeer(otherId,kind,name,'Calling…');const offer=await pc.createOffer();await pc.setLocalDescription(offer);await addSignal('offer',pc.localDescription);if($('#maxCallStatus'))$('#maxCallStatus').textContent='Ringing…'}catch(e){cleanup();alert(e.message||'Could not start call')}finally{makingCall=false}}
async function respondIncoming(call,accept){$('#maxIncomingCall')?.remove();const u=await user();if(!u)return;sessionId=call.id;selectedPeer={id:call.caller_id,name:call.caller_name};currentKind=call.kind;if(!accept){await sb.from('call_sessions').update({status:'declined',ended_at:new Date().toISOString()}).eq('id',call.id);await addSignal('hangup',{}).catch(()=>{});cleanup();return}await sb.from('call_sessions').update({status:'accepted',answered_at:new Date().toISOString()}).eq('id',call.id);await buildPeer(call.caller_id,call.kind,call.caller_name,'Connecting…');const offer=(await sb.from('call_signals').select('sender_id,payload').eq('call_id',call.id).eq('kind','offer').order('created_at',{ascending:false}).limit(1)).data?.[0];if(offer)await handleSignal({sender_id:offer.sender_id,kind:'offer',payload:offer.payload})}
async function endCall(status){if(sessionId){await sb.from('call_sessions').update({status,ended_at:new Date().toISOString()}).eq('id',sessionId);if(me)await addSignal('hangup',{}).catch(()=>{})}cleanup()}
function installButtons(){const head=document.querySelector('.conversation-head');if(!head||head.dataset.maxCalls==='1')return;head.dataset.maxCalls='1';const wrap=document.createElement('div');wrap.className='max-call-actions';wrap.innerHTML='<button type="button" class="max-call-btn voice" id="maxVoiceCall" aria-label="Voice call" title="Voice call"><span>☎</span></button><button type="button" class="max-call-btn video" id="maxVideoCall" aria-label="Video call" title="Video call"><span>▣</span></button>';head.appendChild(wrap);$('#maxVoiceCall').onclick=async()=>{try{const id=await findActivePeer();if(id)await startCall(id,$('#chatName')?.textContent?.trim()||'User','voice');else alert('No active chat.')}catch(e){alert(e.message||'Could not start voice call')}};$('#maxVideoCall').onclick=async()=>{try{const id=await findActivePeer();if(id)await startCall(id,$('#chatName')?.textContent?.trim()||'User','video');else alert('No active chat.')}catch(e){alert(e.message||'Could not start video call')}}}
function watchConversation(){const ensure=()=>setTimeout(installButtons,80);document.addEventListener('click',e=>{if(e.target.closest?.('[data-person]'))ensure();if(e.target.closest?.('#backPeople'))cleanup()});ensure();const mo=new MutationObserver(()=>{const c=document.getElementById('conversation');if(c&&!c.hidden)installButtons()});mo.observe(document.getElementById('app')||document.body,{childList:true,subtree:true})}
async function watchIncoming(){const u=await user();if(!u)return;const ch=sb.channel(`max-call-invite-${u.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'call_sessions',filter:`callee_id=eq.${u.id}`},async p=>{const c=p.new;if(c.status!=='ringing')return;const prof=await sb.from('profiles').select('display_name,username').eq('id',c.caller_id).maybeSingle();const name=prof.data?.display_name||prof.data?.username||'MAX user';incoming({...c,caller_name:name})}).subscribe();window.__MAX_CALL_INVITE_CHANNEL=ch}
window.MAXStartCall=startCall;window.MAXEndCall=endCall;window.addEventListener('beforeunload',cleanup);(async()=>{await user();watchConversation();await watchIncoming()})();
})();
