(()=>{
'use strict';
const sb=window.supabaseClient;
let me=null,selectedPeer=null,callChannel=null,sessionId=null,pc=null,localStream=null,remoteStream=null,currentKind=null,makingCall=false;
const $=(s,r=document)=>r.querySelector(s),esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
async function user(){if(me)return me;const r=await sb.auth.getUser();if(r.error||!r.data.user)return null;me=r.data.user;return me}
function closeChannel(){if(callChannel){sb.removeChannel(callChannel);callChannel=null}}
function cleanup(){closeChannel();if(pc){pc.onicecandidate=null;pc.ontrack=null;pc.onconnectionstatechange=null;pc.close();pc=null}if(localStream){localStream.getTracks().forEach(t=>t.stop());localStream=null}remoteStream=null;sessionId=null;currentKind=null;makingCall=false;$('#maxCallOverlay')?.remove();$('#maxIncomingCall')?.remove()}
function overlay(name,kind,status){$('#maxCallOverlay')?.remove();document.body.insertAdjacentHTML('beforeend',`<section id="maxCallOverlay" class="max-call-overlay"><header class="max-call-top"><span class="avatar">${esc((name||'M').trim().charAt(0).toUpperCase())}</span><div><div class="max-call-title">${esc(name||'MAX contact')}</div><div class="max-call-status" id="maxCallStatus">${esc(status||'Calling…')}</div></div></header><div class="max-call-video-stage"><div class="max-call-avatar" id="maxCallAvatar">${esc((name||'M').trim().charAt(0).toUpperCase())}</div><video id="maxCallRemote" class="max-call-remote" autoplay playsinline></video><video id="maxCallLocal" class="max-call-local" autoplay muted playsinline></video></div><div class="max-call-controls"><button class="max-call-control" id="maxMute">🎙</button>${kind==='video'?'<button class="max-call-control" id="maxCamera">▣</button>':''}<button class="max-call-control end" id="maxEnd">✕</button></div></section>`);$('#maxEnd').onclick=()=>endCall('ended');$('#maxMute').onclick=()=>{const t=localStream?.getAudioTracks?.()[0];if(t){t.enabled=!t.enabled;$('#maxMute').classList.toggle('active',!t.enabled)}};$('#maxCamera')?.addEventListener('click',()=>{const t=localStream?.getVideoTracks?.()[0];if(t){t.enabled=!t.enabled;$('#maxCamera').classList.toggle('active',!t.enabled)}})}
function incoming(id,name,kind,caller){$('#maxIncomingCall')?.remove();document.body.insertAdjacentHTML('beforeend',`<section id="maxIncomingCall" class="max-call-incoming"><h3>${esc(name||'MAX user')}</h3><p>Incoming ${kind==='video'?'video':'voice'} call</p><div class="max-call-incoming-actions"><button class="max-call-decline" id="maxDecline">Decline</button><button class="max-call-accept" id="maxAccept">Accept</button></div></section>`);$('#maxDecline').onclick=()=>respondIncoming(id,false,caller);$('#maxAccept').onclick=()=>respondIncoming(id,true,caller)}
async function send(payload){if(!callChannel)return;await callChannel.send({type:'broadcast',event:'signal',payload})}
async function setupChannel(callId){closeChannel();callChannel=sb.channel(`max-call-${callId}`);callChannel.on('broadcast',{event:'signal'},async ({payload})=>{if(payload?.to!==me?.id)return;if(payload.kind==='offer'&&pc){await pc.setRemoteDescription(payload.description);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);await send({type:'answer',from:me.id,to:payload.from,description:pc.localDescription})}else if(payload.kind==='answer'&&pc){await pc.setRemoteDescription(payload.description)}else if(payload.kind==='ice'&&pc&&payload.candidate){try{await pc.addIceCandidate(payload.candidate)}catch{}}else if(payload.kind==='hangup'){cleanup()}}).subscribe()}
async function setupPeer(otherId,kind,name,isCaller){pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});remoteStream=new MediaStream();$('#maxCallRemote').srcObject=remoteStream;pc.ontrack=e=>e.streams?.[0]?.getTracks().forEach(t=>remoteStream.addTrack(t));pc.onicecandidate=e=>{if(e.candidate)send({type:'ice',from:me.id,to:otherId,candidate:e.candidate})};pc.onconnectionstatechange=()=>{const s=pc.connectionState;if(s==='connected')$('#maxCallStatus').textContent='Connected';if(['failed','disconnected','closed'].includes(s))cleanup()};localStream=await navigator.mediaDevices.getUserMedia({audio:true,video:kind==='video'});$('#maxCallLocal').srcObject=localStream;localStream.getTracks().forEach(t=>pc.addTrack(t,localStream));overlay(name,kind,isCaller?'Calling…':'Connecting…');return pc}
async function startCall(otherId,name,kind){const u=await user();if(!u||makingCall)return;makingCall=true;selectedPeer={id:otherId,name};currentKind=kind;const r=await sb.from('call_sessions').insert({conversation_id:window.__MAX_CHAT_CONVERSATION_ID||null,caller_id:u.id,callee_id:otherId,kind,status:'ringing'}).select('id').single();if(r.error){makingCall=false;return alert(r.error.message)}sessionId=r.data.id;await setupChannel(sessionId);await setupPeer(otherId,kind,name,true);const offer=await pc.createOffer();await pc.setLocalDescription(offer);await send({type:'offer',from:u.id,to:otherId,description:pc.localDescription});makingCall=false}
async function respondIncoming(id,accept,caller){$('#maxIncomingCall')?.remove();const u=await user();if(!u)return;if(!accept){await sb.from('call_sessions').update({status:'declined',ended_at:new Date().toISOString()}).eq('id',id);await setupChannel(id);await send({type:'hangup',from:u.id,to:caller});closeChannel();return}sessionId=id;currentKind=window.__MAX_INCOMING_KIND||'voice';selectedPeer={id:caller,name:window.__MAX_INCOMING_NAME||'MAX user'};await sb.from('call_sessions').update({status:'accepted',answered_at:new Date().toISOString()}).eq('id',id);await setupChannel(id);await setupPeer(caller,currentKind,selectedPeer.name,false)}
async function endCall(status){const u=await user();if(sessionId)await sb.from('call_sessions').update({status,ended_at:new Date().toISOString()}).eq('id',sessionId);if(callChannel&&u)await send({type:'hangup',from:u.id,to:selectedPeer?.id});cleanup()}
function installButtons(){const head=$('.conversation-head');if(!head||head.dataset.maxCalls==='1')return;head.dataset.maxCalls='1';const wrap=document.createElement('div');wrap.className='max-call-actions';wrap.innerHTML='<button type="button" class="max-call-btn" id="maxVoiceCall" title="Voice call">☎</button><button type="button" class="max-call-btn" id="maxVideoCall" title="Video call">▣</button>';head.appendChild(wrap);$('#maxVoiceCall').onclick=()=>{const id=findPeer();if(id)startCall(id,$('#chatName')?.textContent||'User','voice')};$('#maxVideoCall').onclick=()=>{const id=findPeer();if(id)startCall(id,$('#chatName')?.textContent||'User','video')}}
function findPeer(){const row=[...document.querySelectorAll('.person-row')].find(r=>!r.hidden&&r.querySelector('[data-person]')?.dataset.person&&r.querySelector('[data-person]')?.querySelector('span:nth-child(2) b')?.textContent===$('#chatName')?.textContent);return row?.querySelector('[data-person]')?.dataset.person||window.__MAX_CHAT_OTHER_USER_ID||null}
function watchConversation(){document.addEventListener('click',e=>{if(e.target.closest?.('[data-person]'))setTimeout(installButtons,100);if(e.target.closest?.('#backPeople')){$('#maxCallOverlay')?.remove();$('#maxIncomingCall')?.remove()}})}
async function watchIncoming(){const u=await user();if(!u)return;closeChannel();callChannel=sb.channel(`max-user-calls-${u.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'call_sessions',filter:`callee_id=eq.${u.id}`},async p=>{const c=p.new;if(c.status!=='ringing')return;const prof=await sb.from('profiles').select('display_name').eq('id',c.caller_id).maybeSingle();window.__MAX_INCOMING_KIND=c.kind;window.__MAX_INCOMING_NAME=prof.data?.display_name||'MAX user';incoming(c.id,window.__MAX_INCOMING_NAME,c.kind,c.caller_id)}).subscribe()}
window.MAXStartCall=startCall;window.MAXEndCall=endCall;window.addEventListener('beforeunload',()=>cleanup());(async()=>{await user();watchConversation();await watchIncoming()})();
})();